In [0]:
import torch
torch.manual_seed(1)
#ensure consistant results for multiple runs

In [0]:
V_data=[1.,2,3]
V=torch.Tensor(V_data)
print(V)

tensor([1., 2., 3.])


In [0]:
M_data=[[1.,2,3],[4,5,6]]
M=torch.Tensor(M_data)
print(M)

tensor([[1., 2., 3.],
        [4., 5., 6.]])


In [0]:
T_data=[[[1.,2],[3,4]],[[5,6],[7,8]]]
T=torch.Tensor(T_data)
print(T)

tensor([[[1., 2.],
         [3., 4.]],

        [[5., 6.],
         [7., 8.]]])


In [0]:
# random vectors
x=torch.randn((3,4,5))
print(x)

tensor([[[-1.5256, -0.7502, -0.6540, -1.6095, -0.1002],
         [-0.6092, -0.9798, -1.6091, -0.7121,  0.3037],
         [-0.7773, -0.2515, -0.2223,  1.6871,  0.2284],
         [ 0.4676, -0.6970, -1.1608,  0.6995,  0.1991]],

        [[ 0.8657,  0.2444, -0.6629,  0.8073,  1.1017],
         [-0.1759, -2.2456, -1.4465,  0.0612, -0.6177],
         [-0.7981, -0.1316,  1.8793, -0.0721,  0.1578],
         [-0.7735,  0.1991,  0.0457,  0.1530, -0.4757]],

        [[-0.1110,  0.2927, -0.1578, -0.0288,  0.4533],
         [ 1.1422,  0.2486, -1.7754, -0.0255, -1.0233],
         [-0.5962, -1.0055,  0.4285,  1.4761, -1.7869],
         [ 1.6103, -0.7040, -0.1853, -0.9962, -0.8313]]])


In [0]:
# simple algebraic operation
x=torch.tensor([1,2,3])
y=torch.tensor([4,5,6])
z=x+y
print(z)

tensor([5, 7, 9])


In [0]:
#By default, concatenates rows
x_1=torch.randn(2,5)
y_1=torch.randn(3,5)
z_1=torch.cat([x_1,y_1],0)
print(x_1)
print(y_1)
print(z_1)

tensor([[-0.8029,  0.2366,  0.2857,  0.6898, -0.6331],
        [ 0.8795, -0.6842,  0.4533,  0.2912, -0.8317]])
tensor([[-0.5525,  0.6355, -0.3968, -0.6571, -1.6428],
        [ 0.9803, -0.0421, -0.8206,  0.3133, -1.1352],
        [ 0.3773, -0.2824, -2.5667, -1.4303,  0.5009]])
tensor([[-0.8029,  0.2366,  0.2857,  0.6898, -0.6331],
        [ 0.8795, -0.6842,  0.4533,  0.2912, -0.8317],
        [-0.5525,  0.6355, -0.3968, -0.6571, -1.6428],
        [ 0.9803, -0.0421, -0.8206,  0.3133, -1.1352],
        [ 0.3773, -0.2824, -2.5667, -1.4303,  0.5009]])


In [0]:
#concatenate columns
x_2=torch.randn(2,3)
y_2=torch.randn(2,2)
z_2=torch.cat([x_2,y_2],1)
print(x_2)
print(y_2)
print(z_2)

tensor([[ 0.5438, -0.4057,  1.1341],
        [-1.1115,  0.3501, -0.7703]])
tensor([[-0.1473,  0.6272],
        [ 1.0935,  0.0939]])
tensor([[ 0.5438, -0.4057,  1.1341, -0.1473,  0.6272],
        [-1.1115,  0.3501, -0.7703,  1.0935,  0.0939]])


In [0]:
x=torch.randn(2,3,4)
print(x)
print(x.view(2,12))
print(x.view(2,-1)) # default
print(x.view(3,-1)) # default

tensor([[[ 0.4730, -0.4286,  0.5514, -1.5474],
         [ 0.7575, -0.4068, -0.1277,  0.2804],
         [-0.9458, -1.3529,  3.3837, -2.4044]],

        [[ 0.8437,  1.1657,  0.5269,  1.6193],
         [ 0.9462,  0.3512,  1.5728,  1.7185],
         [ 1.7223, -0.3036,  0.2389,  1.3440]]])
tensor([[ 0.4730, -0.4286,  0.5514, -1.5474,  0.7575, -0.4068, -0.1277,  0.2804,
         -0.9458, -1.3529,  3.3837, -2.4044],
        [ 0.8437,  1.1657,  0.5269,  1.6193,  0.9462,  0.3512,  1.5728,  1.7185,
          1.7223, -0.3036,  0.2389,  1.3440]])
tensor([[ 0.4730, -0.4286,  0.5514, -1.5474,  0.7575, -0.4068, -0.1277,  0.2804,
         -0.9458, -1.3529,  3.3837, -2.4044],
        [ 0.8437,  1.1657,  0.5269,  1.6193,  0.9462,  0.3512,  1.5728,  1.7185,
          1.7223, -0.3036,  0.2389,  1.3440]])
tensor([[ 0.4730, -0.4286,  0.5514, -1.5474,  0.7575, -0.4068, -0.1277,  0.2804],
        [-0.9458, -1.3529,  3.3837, -2.4044,  0.8437,  1.1657,  0.5269,  1.6193],
        [ 0.9462,  0.3512,  1.5728,  1.7

In [0]:
x=torch.tensor([1.,2,3],requires_grad=True)
y=torch.tensor([4.,5,6],requires_grad=True)
print(x.grad_fn)
z=x+2*y
print(z)
print(z.grad_fn)

None
tensor([ 9., 12., 15.], grad_fn=<AddBackward0>)


In [0]:
# backward computation
s=z.sum()
print(s)
print(s.grad_fn)

tensor(36., grad_fn=<SumBackward0>)


In [0]:
s.backward()
print(z.grad_fn)
print(x.grad)
print(y.grad)
print(z.grad)

tensor([1., 1., 1.])
tensor([2., 2., 2.])
None


In [0]:
x=torch.randn(2,2)
y=torch.randn(2,2)
print(x.requires_grad,y.requires_grad)
z=x+y
print(z.requires_grad)
print(z.grad_fn)
x=x.requires_grad_()
print(x.requires_grad)
y=y.requires_grad_()
z=x+y
print(z.grad_fn)
print(z.requires_grad)
new_z=z.detach()
print(new_z.grad_fn)

False False
False
None
True
True
None


In [0]:
print(x.requires_grad)
print((x**2).requires_grad)
 
# no frad mode

with torch.no_grad():
    print((x**2).requires_grad)

True
True
False
